os: linux

dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.12.5

git:
  depth: 1

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
