os: linux

dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.12.5

git:
  depth: 1

before_script:
  - make setup-lint

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
