os: linux

dist: bionic

branches:
  only:
    - master

language: go

env: GO111MODULE=on

go:
  - 1.12.5

git:
  depth: 1

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
