// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	ID                 string        `json:"id"`
	CurrentPlayerOrder int           `json:"currentPlayerOrder"`
	Players            []*Player     `json:"players"`
	WordPlayed         []*WordPlayed `json:"wordPlayed"`
	BoardBase          []int         `json:"boardBase"`
	BoardPositioning   []int         `json:"boardPositioning"`
	NumberOfPlayer     int           `json:"numberOfPlayer"`
}

type JoinGame struct {
	GameID string `json:"gameId"`
}

type NewGame struct {
	NumberOfPlayer int `json:"numberOfPlayer"`
}

type Player struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type TakeTurn struct {
	GameID string `json:"gameId"`
	Word   []int  `json:"word"`
}

type WordPlayed struct {
	Player *Player `json:"player"`
	Word   string  `json:"word"`
}
